language: swift
xcode_workspace: OctoPodium.xcworkspace
xcode_scheme: OctoPodium
osx_image: xcode9.3beta

# before_install:
# - pod repo update

script:
  # - xcodebuild -scheme OctoPodium -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' build test
  # - xcodebuild -workspace OctoPodium.xcworkspace -scheme OctoPodium -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build test | xcpretty -c
  - xcodebuild -workspace OctoPodium.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' -scheme OctoPodium -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build test | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)