language: swift
xcode_workspace: OctoPodium.xcworkspace
xcode_scheme: OctoPodium
osx_image: xcode9.3beta
script:
  - xcodebuild -scheme OctoPodium -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)